package pve

import (
	"encoding/json"
	"strconv"
)

// ConfigString reads a scalar value out of a map[string]any decoded from
// a PVE API response (qemu.Config, qemu.Status, qemu.ListSnapshots, and
// similar "map[string]interface{}" endpoints). It exists because PVE's
// wire format is generated by Perl: a value the API spec documents as a
// string can arrive as a JSON number when the underlying Perl scalar
// happened to look numeric (a VM named "123", a tags value of "42", a
// description of "7"). A plain `v, ok := cfg["key"].(string)` treats
// that number as absent and silently takes the "field not set" branch,
// which is wrong and, in some callers, unsafe (e.g. a deleting-tag
// recheck before a destructive operation).
//
// ConfigString returns the value rendered as a string plus true when the
// key is present and holds a JSON string, a JSON number (float64 or
// json.Number, formatted without an exponent or trailing zeros), an
// int/int64 (defensive, in case a caller pre-normalizes), or a bool
// (rendered "1"/"0" to match PVE's own on-wire convention for flags).
// It returns ("", false) when the key is absent, the value is nil, or
// the value is a composite type (map, slice) that has no scalar
// rendering.
func ConfigString(m map[string]any, key string) (string, bool) {
	v, present := m[key]
	if !present {
		return "", false
	}
	return ConfigStringValue(v)
}

// ConfigStringValue applies the same PVE-scalar-tolerant conversion as
// ConfigString to a value already extracted from a config/status map,
// for call sites that range over the map themselves (for k, v := range
// cfg) instead of doing a single keyed lookup.
func ConfigStringValue(v any) (string, bool) {
	switch t := v.(type) {
	case nil:
		return "", false
	case string:
		return t, true
	case float64:
		return strconv.FormatFloat(t, 'f', -1, 64), true
	case json.Number:
		return t.String(), true
	case int:
		return strconv.Itoa(t), true
	case int64:
		return strconv.FormatInt(t, 10), true
	case bool:
		if t {
			return "1", true
		}
		return "0", true
	default:
		// map[string]any, []any, or any other composite/unknown type:
		// no meaningful scalar rendering, treat as absent like the
		// type assertions this helper replaces.
		return "", false
	}
}
