#!/usr/bin/env python3
"""Pure helpers for CF release precompilation (scripts/cf precompile-releases).

Mirrors scripts/bosh compile-releases for the CF deployment: a one-time step
that compiles every CF release against the lab-standardized stemcell so cf
deploy does not have to. Two outcomes are supported:

  - store-ops    — export the compiled tarballs to a Director-reachable store
                   (COMPILED_RELEASES_STORE=s3) and pin them via an ops file
                   (manifests/cf/compiled-releases.yml), used INSTEAD of
                   cf-deployment's operations/use-compiled-releases.yml.
  - director-cache — no reachable store configured (file:// is not reachable by
                   the Director); the Director keeps the compiled packages it
                   built during the no-VM compilation deploy, so cf deploy just
                   drops use-compiled-releases.yml and reuses that cache. The
                   ops file is then only a marker recording the stemcell + mode.

The network/subprocess orchestration lives in scripts/cf; the pure logic here
(release enumeration, manifest rendering, marker generation + detection) is unit
tested in _cfcompile_test.py. Store + real-ops generation reuse _compiled.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import _compiled  # noqa: E402

MODE_MARKER = "# mode: "
CACHE_MODE = "director-cache"
STORE_OPS_MODE = "store-ops"


def parse_release_targets(releases: "list | None") -> "list[dict]":
    """Normalize cf-deployment /releases entries to upload/compile targets.

    Each entry must carry name + version; url + sha1 are optional (sha1 is only
    used as an upload integrity check when present). Non-dict rows are skipped.
    Raises ValueError on a malformed entry or an empty result.
    """
    targets: "list[dict]" = []
    for r in releases or []:
        if not isinstance(r, dict):
            continue
        name = str(r.get("name", "")).strip()
        version = str(r.get("version", "")).strip()
        if not name or not version:
            raise ValueError(f"release entry missing name/version: {r!r}")
        targets.append({
            "name": name,
            "version": version,
            "url": str(r.get("url", "")).strip(),
            "sha1": str(r.get("sha1", "")).strip(),
        })
    if not targets:
        raise ValueError("parse_release_targets: no releases found")
    return targets


def compilation_manifest(
    deployment_name: str, targets: "list[dict]", os_name: str, version: str,
) -> str:
    """Render the no-VM compilation deployment manifest (empty instance_groups).

    Deploying this forces the Director to compile every release's packages
    against the stemcell. Hand-rolled YAML (no PyYAML dependency); all values
    are controlled literals (release names, semver-ish versions, os/version).
    """
    rel_lines = "".join(
        f'- name: {t["name"]}\n  version: "{t["version"]}"\n' for t in targets
    )
    return (
        f"name: {deployment_name}\n"
        "releases:\n"
        f"{rel_lines}"
        "stemcells:\n"
        f'- alias: default\n  os: {os_name}\n  version: "{version}"\n'
        "instance_groups: []\n"
        "update:\n"
        "  canaries: 1\n  max_in_flight: 1\n"
        "  canary_watch_time: 1000-30000\n  update_watch_time: 1000-30000\n  serial: false\n"
    )


def cache_mode_ops(stemcell: str) -> str:
    """Marker file recording that the Director cached compiled packages.

    Comment-only (no release ops) — it is never layered into the deploy; cf
    deploy reads it to decide to drop use-compiled-releases.yml and reuse the
    Director cache. stemcell is "<os>/<version>".
    """
    return "\n".join([
        "---",
        "# GENERATED by `scripts/cf precompile-releases` — do not edit by hand.",
        "# Marker only: the BOSH Director has cached compiled packages for the",
        "# stemcell below. cf deploy drops use-compiled-releases.yml and reuses",
        "# the Director cache; no release URL pins are needed here.",
        f"{_compiled.STEMCELL_MARKER}{stemcell.strip()}",
        f"{MODE_MARKER}{CACHE_MODE}",
        "",
    ])


def precompile_mode(text: str) -> "str | None":
    """Classify a compiled-releases ops file: STORE_OPS_MODE, CACHE_MODE, or None."""
    if "/releases/name=" in text:
        return STORE_OPS_MODE
    for line in text.splitlines():
        s = line.strip()
        if s.startswith(MODE_MARKER) and s[len(MODE_MARKER):].strip() == CACHE_MODE:
            return CACHE_MODE
    return None


def precompile_state(ops_text: str, current_stemcell: str) -> str:
    """Decide what cf deploy should do given the ops file and current stemcell.

    Returns:
        "absent"          — no usable precompile result; run precompile-releases.
        "mismatch"        — precompiled for a different stemcell; re-run.
        STORE_OPS_MODE    — layer the ops file instead of use-compiled-releases.
        CACHE_MODE        — drop use-compiled-releases; reuse the Director cache.
    """
    if not ops_text or not ops_text.strip():
        return "absent"
    sc = _compiled.stemcell_from_ops(ops_text)
    if sc and current_stemcell and sc.strip() != current_stemcell.strip():
        return "mismatch"
    return precompile_mode(ops_text) or "absent"
